//Contains header and footer for site

import './styles/globals.scss'
import './styles/kanban/kanban-board.scss'
import './styles/kanban/kanban-card.scss'
import './styles/kanban/kanban-card-row.scss'
import './styles/kanban/kanban-column.scss'

import './styles/common/header.scss'
import './styles/common/footer.scss'

import titles from './data/titles.json'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import PageHeader  from "./components/common/page-header";
import PageFooter  from "./components/common/page-footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PageHeader/>
        {children}
        <PageFooter/>
      </body>
    </html>
  )
}
